/** Everything the film shows on screen, in one place. */

export type Brand = {
  name: string;
  logo: string;
  /** Browser tab label. */
  tab: string;
  url: string;
  /** Page background inside the app. */
  surface: string;
  /** Sidebar background. */
  sidebar: string;
  /** User message bubble. */
  bubble: string;
  /** Composer border. */
  border: string;
  composer: string;
  /** Shown in the middle of an empty chat. */
  greeting: string;
  /** The small print under the composer. */
  disclaimer: string;
};

export const BRANDS: Record<string, Brand> = {
  chatgpt: {
    name: "ChatGPT",
    logo: "/openai.svg",
    tab: "Stock Predictor",
    url: "chatgpt.com/c/68f2a1",
    surface: "bg-white",
    sidebar: "bg-[#f9f9f9]",
    bubble: "bg-[#f1f1f1]",
    border: "border-ink-900/12",
    composer: "Ask anything",
    greeting: "What can I help with?",
    disclaimer: "ChatGPT can make mistakes. Check important info.",
  },
  claude: {
    name: "Claude",
    logo: "/claude-color.svg",
    tab: "New chat",
    url: "claude.ai/new",
    surface: "bg-[#faf9f5]",
    sidebar: "bg-[#f2f0e9]",
    bubble: "bg-[#eeebe0]",
    border: "border-[#d9d4c4]",
    composer: "How can I help you today?",
    greeting: "How can I help you today?",
    disclaimer: "Claude can make mistakes. Please double-check responses.",
  },
  copilot: {
    name: "Copilot",
    logo: "/copilot-color.svg",
    tab: "Copilot",
    url: "copilot.microsoft.com",
    surface: "bg-[#f9fbfe]",
    sidebar: "bg-[#eef3fb]",
    bubble: "bg-[#e4ecfa]",
    border: "border-[#cddcf0]",
    composer: "Message Copilot",
    greeting: "Let's get to work",
    disclaimer: "AI-generated content may be incorrect.",
  },
  meta: {
    name: "Meta AI",
    logo: "/meta-color.svg",
    tab: "Meta AI",
    url: "meta.ai/c/4b21",
    surface: "bg-white",
    sidebar: "bg-[#f4f7fd]",
    bubble: "bg-[#e8f0fe]",
    border: "border-[#cfe0fb]",
    composer: "Ask Meta AI anything",
    greeting: "What's on your mind?",
    disclaimer: "Messages are generated by AI and may be inaccurate.",
  },
  kimi: {
    name: "Kimi",
    logo: "/kimi.svg",
    tab: "Kimi",
    url: "kimi.com/chat/9f10",
    surface: "bg-[#fcfcfb]",
    sidebar: "bg-[#f4f4f2]",
    bubble: "bg-[#efeeea]",
    border: "border-ink-900/12",
    composer: "Message Kimi",
    greeting: "Ask me anything",
    disclaimer: "Kimi can make mistakes. Verify important details.",
  },
  grok: {
    name: "Grok",
    logo: "/grok.svg",
    tab: "Grok",
    url: "grok.com/chat/7c33",
    surface: "bg-white",
    sidebar: "bg-[#f5f5f5]",
    bubble: "bg-[#efefef]",
    border: "border-ink-900/14",
    composer: "Ask anything",
    greeting: "What do you want to know?",
    disclaimer: "Grok can make mistakes. Verify its outputs.",
  },
  gemini: {
    name: "Gemini",
    logo: "/gemini-color.svg",
    tab: "Gemini",
    url: "gemini.google.com/app",
    surface: "bg-white",
    sidebar: "bg-[#f0f4fc]",
    bubble: "bg-[#e6ecfb]",
    border: "border-[#d3ddf8]",
    composer: "Ask Gemini",
    greeting: "Hello, Edison",
    disclaimer: "Gemini can make mistakes, so double-check it.",
  },
  deepseek: {
    name: "DeepSeek",
    logo: "/deepseek-color.svg",
    tab: "DeepSeek",
    url: "chat.deepseek.com/a/2d80",
    surface: "bg-[#fbfcff]",
    sidebar: "bg-[#eff2fd]",
    bubble: "bg-[#e6ebfb]",
    border: "border-[#d4dcfb]",
    composer: "Message DeepSeek",
    greeting: "How can I help today?",
    disclaimer: "AI-generated, for reference only.",
  },
};

export const PROJECT = "Stock Predictor";

/** Sidebar chat history, per kind of work. */
export const RECENTS = {
  coding: ["Stock Predictor", "Backtest engine", "Feature pipeline"],
  research: ["On-device embeddings", "Vector store costs", "Latency budget"],
  writing: ["Launch post", "Positioning notes", "Waitlist email"],
} as const;

export type Message =
  | { role: "user"; text: string }
  | {
      role: "assistant";
      text: string;
      code?: readonly string[];
      filename?: string;
      table?: {
        head: readonly string[];
        rows: readonly (readonly string[])[];
      };
      sources?: readonly string[];
      after?: string;
    };

export type Variation = {
  kind: keyof typeof RECENTS;
  /** Sidebar title and tab label. */
  title: string;
  messages: readonly Message[];
  /** What Coere carries into the next model. */
  capsule: readonly string[];
  /** How the destination picks it up. */
  reply: readonly string[];
};

/** The main story: a real coding project in ChatGPT. */
export const CODING: Variation = {
  kind: "coding",
  title: "Stock Predictor",
  messages: [
    {
      role: "user",
      text: "Working on Stock Predictor. Daily OHLCV for 40 tickers from yfinance, 2019 to now, stored as parquet.",
    },
    {
      role: "assistant",
      text: "Build the features off returns rather than raw prices so the series is stationary:",
      filename: "features.py",
      code: [
        "def build_features(df):",
        "    df['ret_1d'] = df.close.pct_change()",
        "    df['rsi_14'] = rsi(df.close, 14)",
        "    df['ema_20'] = df.close.ewm(span=20).mean()",
        "    return df.dropna()",
      ],
      after: "Then walk-forward validate with a six month embargo.",
    },
    {
      role: "user",
      text: "Done. 2 layer LSTM, 64 units, dropout 0.2. Sharpe 1.18 on the 2024 holdout, max drawdown 9.4%.",
    },
  ],
  capsule: [
    "Project: Stock Predictor, daily OHLCV for 40 tickers since 2019",
    "Features: returns, RSI 14, EMA 20 and 50, 30 day lookback",
    "Model: 2 layer LSTM, 64 units, dropout 0.2, val loss 0.031",
    "Decided: walk-forward split, six month embargo, MLflow logging",
    "Holdout: Sharpe 1.18, max drawdown 9.4%",
    "Next: backtest engine with slippage",
  ],
  reply: [
    "Picking up Stock Predictor exactly where you left it.",
    "Walk-forward split with the six month embargo is in place, Sharpe 1.18 on the 2024 holdout.",
    "Let's build the backtest engine with slippage next.",
  ],
};

/** Same project, research mode. */
export const RESEARCH: Variation = {
  kind: "research",
  title: "On-device embeddings",
  messages: [
    {
      role: "user",
      text: "Which embedding model should run in the browser for retrieval over saved chats?",
    },
    {
      role: "assistant",
      text: "Three candidates fit in a browser budget:",
      table: {
        head: ["Model", "Size", "MTEB"],
        rows: [
          ["bge-small-en", "33M", "62.2"],
          ["all-MiniLM-L6", "22M", "56.3"],
          ["gte-small", "33M", "61.4"],
        ],
      },
      sources: ["MTEB leaderboard", "WebGPU benchmarks"],
    },
    {
      role: "user",
      text: "Going with bge-small. Quantised to int8 it stays under 40ms per chunk on an M1.",
    },
  ],
  capsule: [
    "Question: embedding model for in-browser retrieval",
    "Shortlist: bge-small, MiniLM-L6, gte-small",
    "Chosen: bge-small, int8, under 40ms per chunk on M1",
    "Constraint: no server round trip, nothing stored",
  ],
  reply: [
    "Carrying over the embedding decision.",
    "bge-small at int8 under 40ms per chunk, all in the browser.",
    "Want me to size the index for 5,000 saved chats?",
  ],
};

/** Same project, writing mode. */
export const WRITING: Variation = {
  kind: "writing",
  title: "Launch post",
  messages: [
    {
      role: "user",
      text: "Draft the launch post for Coere. Plain, no hype, one idea per paragraph.",
    },
    {
      role: "assistant",
      text: "Opening draft:",
      after:
        "“You already explained your project once. Coere is the reason you never have to explain it again. It carries what you decided, not just what you typed, into whichever model you open next.”",
    },
    {
      role: "user",
      text: "Keep that. Cut the second paragraph, and end on the install line instead.",
    },
  ],
  capsule: [
    "Piece: Coere launch post",
    "Voice: plain, no hype, one idea per paragraph",
    "Kept: opening on explaining your project once",
    "Cut: second paragraph, end on the install line",
  ],
  reply: [
    "Continuing the launch post in your voice.",
    "Opening kept, second paragraph cut, ending on the install line.",
    "Here is the tightened version.",
  ],
};

export const VARIATIONS = [CODING, RESEARCH, WRITING] as const;

/**
 * Act 3 cuts between products with the windows held perfectly still. The gaps
 * shrink from half a second to a strobe, then it lands and holds.
 */
export const MONTAGE: { source: string; dest: string; variation: number }[] = [
  { source: "gemini", dest: "copilot", variation: 1 },
  { source: "grok", dest: "meta", variation: 2 },
  { source: "kimi", dest: "deepseek", variation: 0 },
  { source: "copilot", dest: "claude", variation: 1 },
  { source: "meta", dest: "gemini", variation: 2 },
  { source: "deepseek", dest: "chatgpt", variation: 0 },
  { source: "claude", dest: "grok", variation: 1 },
  { source: "chatgpt", dest: "kimi", variation: 2 },
  { source: "gemini", dest: "deepseek", variation: 0 },
  { source: "kimi", dest: "meta", variation: 1 },
  { source: "grok", dest: "copilot", variation: 2 },
  { source: "meta", dest: "claude", variation: 0 },
  { source: "deepseek", dest: "gemini", variation: 1 },
  { source: "copilot", dest: "grok", variation: 2 },
  { source: "claude", dest: "chatgpt", variation: 0 },
  { source: "chatgpt", dest: "claude", variation: 0 },
];

/** A second, then a tenth faster each switch, settling at half a second. */
export function montageDelay(step: number) {
  return Math.max(500, 1000 - step * 100);
}

/** The switch where the cadence has settled, and the zoom out begins. */
export const MONTAGE_SETTLES = 5;

const BRAND_KEYS = Object.keys(BRANDS);

/**
 * The closing wall: the same hand-off happening everywhere at once. Slots are
 * placed around the middle of the stage, which the hero pair keeps.
 */
const WALL_SLOTS: [number, number][] = [
  // tiles are 228 wide, so slots sit 248 apart and never overlap
  [16, 30],
  [264, 30],
  [512, 30],
  [760, 30],
  [1008, 30],
  [16, 132],
  [264, 132],
  [512, 132],
  [760, 132],
  [1008, 132],
  [16, 256],
  [1008, 256],
  [16, 358],
  [1008, 358],
  [16, 500],
  [264, 500],
  [512, 500],
  [760, 500],
  [1008, 500],
  [140, 602],
  [388, 602],
  [636, 602],
  [884, 602],
];

export const WALL = WALL_SLOTS.map(([x, y], index) => {
  const source = BRAND_KEYS[(index * 3 + 1) % BRAND_KEYS.length];
  let dest = BRAND_KEYS[(index * 5 + 4) % BRAND_KEYS.length];
  if (dest === source) {
    dest = BRAND_KEYS[(index * 5 + 5) % BRAND_KEYS.length];
  }
  return {
    x,
    y,
    source,
    dest,
    // fans out from the middle rather than sweeping in one direction
    delay: 0.05 * ((index * 7) % 11),
  };
});

export const TRANSFER = {
  tokensBefore: 12480,
  tokensAfter: 310,
  secondsBefore: 278,
  secondsAfter: 6,
  sourceChats: 3,
};

/** The user's saved transfers. */
export const TRANSFERS = [
  {
    project: "Stock Predictor",
    from: "chatgpt",
    to: "claude",
    tokens: 12170,
    seconds: 272,
    when: "Just now",
  },
  {
    project: "On-device embeddings",
    from: "claude",
    to: "gemini",
    tokens: 8940,
    seconds: 192,
    when: "2 hours ago",
  },
  {
    project: "Launch post",
    from: "gemini",
    to: "copilot",
    tokens: 6320,
    seconds: 154,
    when: "Yesterday",
  },
  {
    project: "Supabase RLS policies",
    from: "meta",
    to: "chatgpt",
    tokens: 4180,
    seconds: 118,
    when: "Yesterday",
  },
] as const;

export const TOTALS = {
  transfers: 128,
  tokensSaved: 1_420_000,
  secondsSaved: 34_800,
};
